# Generated by Django 4.2.6 on 2023-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('titulo', models.CharField(max_length=100)),
                ('github_link', models.URLField()),
                ('introduccion', models.TextField()),
                ('herramientas', models.TextField()),
                ('resultadosLogros', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'infoProyecto',
                'verbose_name_plural': 'infoProyectos',
            },
        ),
    ]
