# Generated by Django 4.2.6 on 2023-11-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoproyectos',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='infoproyectos',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
