# Generated by Django 4.2.4 on 2023-11-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0002_rename_created_at_infoproyectos_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproyectos',
            name='link_proyecto',
            field=models.URLField(null=True),
        ),
    ]
