# Generated by Django 4.2.4 on 2023-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0003_infoproyectos_link_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproyectos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proyectos'),
        ),
    ]
