# Generated by Django 4.2.4 on 2023-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0004_alter_infoproyectos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproyectos',
            name='github_link',
            field=models.URLField(null=True),
        ),
    ]
