# Generated by Django 4.2.4 on 2023-11-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0005_alter_infoproyectos_github_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoProyectos',
            new_name='InfoProyectos2',
        ),
    ]
