# Generated by Django 4.2.4 on 2023-11-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0006_rename_infoproyectos_infoproyectos2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoproyectos2',
            options={'verbose_name': 'infoProyecto2', 'verbose_name_plural': 'infoProyectos2'},
        ),
        migrations.AlterField(
            model_name='infoproyectos2',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoproyectos2',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos'),
        ),
        migrations.AlterField(
            model_name='infoproyectos2',
            name='link_proyecto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
